# =====================================================================================
# SolidGroundUX - Fantasy UI Style
# -------------------------------------------------------------------------------------
# Type    : library
# Group   : Styles
# Purpose : Purple, gold, and cyan semantic UI style mapping
# =====================================================================================

SAY_DATE_DEFAULT=0
SAY_SHOW_DEFAULT="label"
SAY_COLORIZE_DEFAULT="label"
SAY_DATE_FORMAT="%Y-%m-%d %H:%M:%S"

LBL_CNCL="CANCEL"
LBL_EMPTY="     "
LBL_END="END"
LBL_FAIL="ERROR"
LBL_INFO="INFO"
LBL_OK="SUCCESS"
LBL_STRT="START"
LBL_WARN="WARNING"
LBL_DEBUG="DEBUG"

ICO_CNCL=$'[STOP]'
ICO_EMPTY=$''
ICO_END=$'[END]'
ICO_FAIL=$'[ERR]'
ICO_INFO=$'[INF]'
ICO_OK=$'[OK]'
ICO_STRT=$'[RUN]'
ICO_WARN=$'[WRN]'
ICO_DEBUG=$'[DBG]'

SYM_CNCL="(-)"
SYM_EMPTY=""
SYM_END="<<<"
SYM_FAIL="(X)"
SYM_INFO="(+)"
SYM_OK="(+)"
SYM_STRT=">>>"
SYM_WARN="(!)"
SYM_DEBUG="(~)"

MSG_CLR_INFO=$BRIGHT_CYAN
MSG_CLR_STRT=$BRIGHT_PURPLE
MSG_CLR_OK=$BRIGHT_GOLD
MSG_CLR_WARN=$BRIGHT_ORANGE
MSG_CLR_FAIL=$BRIGHT_PINK
MSG_CLR_CNCL=$DARK_PURPLE
MSG_CLR_END=$BRIGHT_GOLD
MSG_CLR_EMPTY=$DARK_SILVER
MSG_CLR_DEBUG=$BRIGHT_MAGENTA

PROG_BAR_CLR=$BRIGHT_PURPLE
PROG_IND_CLR=$BRIGHT_GOLD
PROG_TEXT_CLR=$BRIGHT_CYAN

SGND_UI_BORDER=$BRIGHT_PURPLE
SGND_UI_LABEL=$BRIGHT_CYAN
SGND_UI_VALUE=$BRIGHT_GOLD
SGND_UI_COMMIT=$BRIGHT_ORANGE
SGND_UI_DRYRUN=$TEAL
SGND_UI_ENABLED=$BRIGHT_WHITE
SGND_UI_DISABLED=$DARK_PURPLE
SGND_UI_ON=$BRIGHT_GOLD
SGND_UI_OFF=$DARK_PURPLE
SGND_UI_INPUT=$BRIGHT_GOLD
SGND_UI_PROMPT=$BRIGHT_PURPLE
SGND_UI_INVALID=$BRIGHT_PINK
SGND_UI_VALID=$BRIGHT_GOLD
SGND_UI_SUCCESS=$BRIGHT_GOLD
SGND_UI_ERROR=$BRIGHT_PINK
SGND_UI_TEXT=$SILVER
SGND_UI_DEFAULT=$DARK_SILVER
