# =====================================================================================
# SolidGroundUX - Dark UI Style
# -------------------------------------------------------------------------------------
# Type    : library
# Group   : Styles
# Purpose : Balanced dark terminal semantic UI style mapping
# =====================================================================================

SAY_DATE_DEFAULT=0
SAY_SHOW_DEFAULT="label"
SAY_COLORIZE_DEFAULT="label"
SAY_DATE_FORMAT="%Y-%m-%d %H:%M:%S"

LBL_CNCL="CANCEL"
LBL_EMPTY="     "
LBL_END="END"
LBL_FAIL="ERROR"
LBL_INFO="INFO"
LBL_OK="SUCCESS"
LBL_STRT="START"
LBL_WARN="WARNING"
LBL_DEBUG="DEBUG"

ICO_CNCL=$'[STOP]'
ICO_EMPTY=$''
ICO_END=$'[END]'
ICO_FAIL=$'[ERR]'
ICO_INFO=$'[INF]'
ICO_OK=$'[OK]'
ICO_STRT=$'[RUN]'
ICO_WARN=$'[WRN]'
ICO_DEBUG=$'[DBG]'

SYM_CNCL="(-)"
SYM_EMPTY=""
SYM_END="<<<"
SYM_FAIL="(X)"
SYM_INFO="(+)"
SYM_OK="(+)"
SYM_STRT=">>>"
SYM_WARN="(!)"
SYM_DEBUG="(~)"

MSG_CLR_INFO=$SILVER
MSG_CLR_STRT=$BRIGHT_CYAN
MSG_CLR_OK=$BRIGHT_GREEN
MSG_CLR_WARN=$BRIGHT_ORANGE
MSG_CLR_FAIL=$BRIGHT_RED
MSG_CLR_CNCL=$YELLOW
MSG_CLR_END=$BRIGHT_CYAN
MSG_CLR_EMPTY=$DARK_SILVER
MSG_CLR_DEBUG=$BRIGHT_MAGENTA

PROG_BAR_CLR=$GRAY
PROG_IND_CLR=$DARK_GRAY
PROG_TEXT_CLR=$SILVER

SGND_UI_BORDER=$DARK_GRAY
SGND_UI_LABEL=$SILVER
SGND_UI_VALUE=$BRIGHT_WHITE
SGND_UI_COMMIT=$BRIGHT_ORANGE
SGND_UI_DRYRUN=$GREEN
SGND_UI_ENABLED=$BRIGHT_WHITE
SGND_UI_DISABLED=$DARK_GRAY
SGND_UI_INPUT=$SILVER
SGND_UI_PROMPT=$DARK_GRAY
SGND_UI_INVALID=$BRIGHT_ORANGE
SGND_UI_VALID=$SILVER
SGND_UI_SUCCESS=$SILVER
SGND_UI_ERROR=$BRIGHT_RED
SGND_UI_TEXT=$SILVER
SGND_UI_DEFAULT=$GRAY
