# ==================================================================================
# SolidGroundUX - Deployment and Release Management
# ----------------------------------------------------------------------------------
# Metadata:
#   Version     : 2.1
#   Build       : 2625813
#   Checksum    : 2241f46bb94f5015f9676caf34eda9a05357b60210261819c5b433e36d279ab7
#   Source      : deployment_preface.sh
#   Type        : documentation
#   Group       : Deployment
#   Purpose     : Describe the SolidGroundUX deployment and release-management workflow
#
# Attribution:
#   Developers  : Mark Fieten
#   Company     : Testadura Consultancy
#   Client      : -
#   Copyright   : © 2025 - 2026 Testadura Consultancy
#   License     : Licensed under the Testadura Non-Commercial License (TD-NC) v1.1.
# ==================================================================================
# - Deployment ----------------------------------------------------------------------
#
# > SolidGroundUX deployment is built around three complementary tools:
#
# >     prepare-release.sh
# >         Builds complete, versioned release artifacts from a workspace.
#
# >     deploy-workspace.sh
# >         Streams selected development files directly to a target machine.
#
# >     release-manager.sh
# >         Standalone release acquisition, installation, update, rollback,
# >         reinstallation, and removal.
#
# > Together they cover the two main deployment scenarios:
#
# >     Development deployment
# >         Fast transfer of selected workspace files without creating a formal release.
#
# >     Release deployment
# >         Creation, validation, installation, update, rollback, and removal of
# >         complete SolidGroundUX releases.
#
# > The release manager is deliberately self-sufficient. It always carries a small
# > standalone UI and default-theme fallback so it can bootstrap a clean machine or
# > recover a damaged installation. When a healthy SolidGroundUX framework is available
# > at the selected target root, the manager may reuse the normal framework UI primitives
# > and active theme without making the release engine dependent on them.
#
# -- Release Preparation -------------------------------------------------------------
#
# > prepare-release.sh creates the canonical project release set in the workspace release
# > output directory. These build artifacts are not copied into the target-root release
# > state; release-manager.sh admits them there only when a package is acquired/installed.
#
# > A release contains a complete target-root filesystem image rather than a binary
# > patch. The distributable ZIP contains:
#
# >     release-package.info
# >     <Product>-<version>.<build>.tar.gz
# >     <Product>-<version>.<build>.tar.gz.sha256
# >     <Product>-<version>.<build>.manifest
# >     <Product>-<version>.<build>.manifest.sha256
# >     <Product>-<version>.<build>.removed
# >     <Product>-<version>.<build>.removed.sha256
#
# > SolidGroundUX framework packages additionally contain release-manager.sh at ZIP root
# > so the package can bootstrap a clean machine. Generic project packages omit the
# > manager and are consumed by an already installed Release Manager.
#
# > The tar archive contains the complete target-root tree for that release.
#
# > release-package.info is the package shipping label. It identifies the package format,
# > project slug, product, version, build, and release name without requiring the manager
# > to inspect the tar archive first.
#
# > The normal manifest describes the paths contained in the release.
#
# > The removed manifest is generated by comparing the previous release manifest with
# > the new one. It contains paths that existed in the previous release but no longer
# > belong to the new release. release-manager.sh applies this file during an update.
#
# > Example:
#
# >     prepare-release.sh
#
# > Useful examples:
#
# >     prepare-release.sh --updatebuild
# >     prepare-release.sh --updateversion
# >     prepare-release.sh --bumpminor
# >     prepare-release.sh --bumpmajor
# >     prepare-release.sh --dryrun
#
# > prepare-release.sh is a development/release-authoring tool and therefore uses the
# > normal SolidGroundUX framework runtime.
#
# -- Release Manager -----------------------------------------------------------------
#
# > release-manager.sh is the canonical installation and release-lifecycle tool.
#
# > It replaces the former separate installer, updater, and uninstaller scripts.
#
# > Its state model is intentionally filesystem-based and project-aware.
#
# > SolidGroundUX retains the canonical locations:
#
# >     /var/lib/solidgroundux/releases
# >     /var/lib/solidgroundux/archive/<release>
#
# > Additional projects keep their own state beneath:
#
# >     /var/lib/solidgroundux/projects/<project>/releases
# >     /var/lib/solidgroundux/projects/<project>/archive/<release>
#
# > The highest versioned archive directory represents the currently installed release
# > for that project. No separate current-version database is required.
#
# > A first install consists of validating and extracting a complete release archive.
#
# > A later install is treated as an update. The new release is extracted normally,
# > and its .removed manifest is applied so files that disappeared from the release
# > are removed from the active installation.
#
# > Rollback installs a selected archived release again and removes files that belong
# > only to the newer release. Newer archived releases are returned to releases/ so
# > the highest remaining archive directory continues to represent the active version.
#
# > Removal removes the active release contents and returns archived release sets to
# > releases/, preserving them for later reinstallation.
#
# -- First Installation --------------------------------------------------------------
#
# > SolidGroundUX release ZIPs contain release-manager.sh together with the complete
# > prepared release set and release-package.info.
#
# > A first installation therefore remains deliberately small:
#
# >     cd /tmp
# >     unzip SolidGroundUX-<version>-release.zip
# >     sudo ./release-manager.sh
#
# > Because the ZIP-root manager is not yet running from its canonical installed
# > location, the default target root is `/`. In interactive mode the target root is
# > still asked explicitly before installation proceeds.
#
# > On first run, release-manager.sh:
#
# >     - Reads release-package.info and identifies the package.
# >     - Asks for or resolves the target root and other stateful parameters.
# >     - Creates the required release-management directories.
# >     - Validates the release artifacts, checksums, manifests, and archive paths.
# >     - Admits the release into the selected project's releases directory.
# >     - Installs the complete tar archive into the selected target root.
# >     - Moves the installed release set into that project's archive history.
# >     - Uses the release-manager.sh installed by the SolidGroundUX tar as the canonical
# >       `/var/lib/solidgroundux/release-manager.sh` copy.
# >     - Creates or verifies the public release-manager wrapper.
# >     - Cleans only known temporary bootstrap files after successful installation.
#
# > The bootstrap copy never overwrites the canonical manager merely because it is
# > executing from another path. The installed release owns the permanent manager copy.
#
# -- Interactive Use -----------------------------------------------------------------
#
# > Running release-manager.sh without an action opens the interactive Release Manager:
#
# >     sudo /var/lib/solidgroundux/release-manager.sh
#
# > Parameter values are presented as questions and persisted as standalone state so the
# > accepted values become defaults on later runs. Typical parameters include:
#
# >     - Target root.
# >     - Project.
# >     - Package source.
# >     - GitHub repository.
# >     - Release selector.
# >
# > The menu provides the release lifecycle actions:
#
# >     - Check GitHub for the latest release.
# >     - Download the latest release.
# >     - Update to the latest release.
# >     - Install a local package/release.
# >     - Select an archived version for reinstallation or rollback.
# >     - Remove the selected project.
# >     - Select the active project for project-specific operations.
#
# > The standalone fallback UI is based on the SolidGroundUX default theme. When a
# > healthy SolidGroundUX framework is available at the selected target root, the manager
# > may switch to the normal framework UI primitives and active theme.
#
# -- Command-line Use ----------------------------------------------------------------
#
# > Command-line actions invoke the same functions exposed by the interactive menu.
# > Arguments therefore select an action and/or provide parameter values; they do not
# > form a separate release workflow.
#
# > Check GitHub without changing the machine:
#
# >     release-manager.sh --check
#
# > Download the latest release without installing it:
#
# >     release-manager.sh --download
#
# > Check, download if required, and install the latest GitHub release:
#
# >     release-manager.sh --update
#
# > Install the newest release already available locally:
#
# >     release-manager.sh --install
#
# > Install directly from a package ZIP or URL:
#
# >     release-manager.sh --install --source /tmp/SolidGroundUX-release.zip
#
# >     release-manager.sh --install \
# >         --source https://example.org/releases/SolidGroundUX-release.zip
#
# > Roll back to the previous archived release:
#
# >     release-manager.sh --rollback
#
# > Roll back to a specific archived release:
#
# >     release-manager.sh --rollback --release 2.1.2624102
#
# > Remove the selected project:
#
# >     release-manager.sh --remove
#
# > Select a known project explicitly:
#
# >     release-manager.sh --project solidground-management-modules --install
#
# > Run an action without questions or confirmations:
#
# >     release-manager.sh --update --auto
#
# > Preview filesystem changes:
#
# >     release-manager.sh --update --dryrun
#
# > Override the default GitHub repository:
#
# >     release-manager.sh --check --repo Testadura-Mark/SolidGroundUX
#
# > Alternate target roots can be supplied for development, testing, or recovery:
#
# >     release-manager.sh --install \
# >         --target-root /mnt/testroot \
# >         --source /tmp/SolidGroundUX-release.zip
#
# -- GitHub Acquisition --------------------------------------------------------------
#
# > GitHub is the default authoritative source for determining the latest published
# > SolidGroundUX release. Generic project packages can always be supplied directly by
# > file or URL; project-specific online discovery can be added through project metadata
# > without changing the package-installation engine.
#
# > release-manager.sh asks GitHub which SolidGroundUX release is current before downloading.
#
# > If that release is already present under archive/ it is considered installed.
#
# > If it is already present under releases/ it is considered downloaded.
#
# > In either case, the release manager avoids downloading the same release again.
#
# > New downloads are staged in a temporary directory first. The ZIP is extracted,
# > the contained release identity is checked, required release files are verified,
# > checksums are validated, and release paths are checked for unsafe traversal.
#
# > Only a valid release set is admitted into releases/.
#
# -- Relationship to deploy-workspace.sh --------------------------------------------
#
# > deploy-workspace.sh serves a different purpose from release-manager.sh.
#
# > It is intended for rapid development deployment, where selected files from a
# > workspace need to be transferred directly to a test or development machine.
#
# > It supports:
#
# >     - Local or SSH deployment.
# >     - Optional directory filtering.
# >     - Filenames and shell-style masks.
# >     - Changed-after filtering.
# >     - Deployment since the last successful transfer.
# >     - Dry-run operation.
# >     - Persistent deployment settings.
#
# > Example:
#
# >     deploy-workspace.sh # >         --remote sysadmin@td-pdc # >         --source ~/dev/target-root # >         --match '*.sh'
#
# > Incremental deployment:
#
# >     deploy-workspace.sh # >         --remote sysadmin@td-pdc # >         --since-last
#
# > deploy-workspace.sh does not create an installed release record and does not
# > participate in archive-based rollback. It is therefore ideal during development,
# > while prepare-release.sh plus release-manager.sh provide the formal release path.
#
# -- How the Three Tools Relate -------------------------------------------------------
#
# . Images
#   deployment-model.png :: SolidGroundUX Deployment Model
#
# > This keeps the deployment architecture small, deterministic, and easy to inspect
# > or manipulate directly when necessary.
#
# -- Integrity and Recovery ----------------------------------------------------------
#
# > Release integrity is validated before installation by checking the supplied
# > SHA-256 sidecar files and release paths.
#
# > The release engine intentionally remains independent of the installed framework.
# > Its standalone UI and default-theme fallback are always available. Framework UI
# > primitives and the active theme are used only when they can be loaded successfully.
#
# > As a result, the canonical copy at:
#
# >     /var/lib/solidgroundux/release-manager.sh
#
# > remains usable for update, rollback, reinstallation, or removal even if the live
# > SolidGroundUX installation is incomplete or damaged.
#
# > This independence is a core deployment design principle.
