# ==================================================================================
# SolidGroundUX - Deployment and Release Management
# ----------------------------------------------------------------------------------
# Metadata:
#   Version     : 2.0
#   Build       : 2623104
#   Checksum    : 8f3389d0e99891eac8348979c08a752056237b24299aad226ed1f2b9fe0651e4
#   Source      : deployment_preface.sh
#   Type        : documentation
#   Group       : Deployment
#   Purpose     : Describe the SolidGroundUX deployment and release-management workflow
#
# Attribution:
#   Developers  : Mark Fieten
#   Company     : Testadura Consultancy
#   Client      : -
#   Copyright   : © 2025 - 2026 Testadura Consultancy
#   License     : Licensed under the Testadura Non-Commercial License (TD-NC) v1.1.
# ==================================================================================
# - Deployment ----------------------------------------------------------------------
#
# > SolidGroundUX deployment is built around three complementary tools:
#
# >     prepare-release.sh
# >         Builds complete, versioned release artifacts from a workspace.
#
# >     deploy-workspace.sh
# >         Streams selected development files directly to a target machine.
#
# >     release-manager.sh
# >         Standalone release acquisition, installation, update, rollback,
# >         reinstallation, and removal.
#
# > Together they cover the two main deployment scenarios:
#
# >     Development deployment
# >         Fast transfer of selected workspace files without creating a formal release.
#
# >     Release deployment
# >         Creation, validation, installation, update, rollback, and removal of
# >         complete SolidGroundUX releases.
#
# > The release manager is deliberately framework-independent. It does not source
# > SolidGroundUX libraries or require a working framework installation. This allows
# > it to bootstrap a clean machine and to repair, update, roll back, or remove an
# > installation even when the installed framework is unavailable or damaged.
#
# -- Release Preparation -------------------------------------------------------------
#
# > prepare-release.sh creates the canonical SolidGroundUX release set.
#
# > A release contains a complete target-root filesystem image rather than a binary
# > patch. Typical artifacts include:
#
# >     SolidGroundUX-<version>.tar.gz
# >     SolidGroundUX-<version>.tar.gz.sha256
# >     SolidGroundUX-<version>.manifest
# >     SolidGroundUX-<version>.manifest.sha256
# >     SolidGroundUX-<version>.removed
# >     SolidGroundUX-<version>.removed.sha256
# >     SHA256SUMS
#
# > The tar archive contains the complete framework tree for that release.
#
# > The normal manifest describes the paths contained in the release.
#
# > The removed manifest is generated by comparing the previous release manifest with
# > the new one. It contains paths that existed in the previous release but no longer
# > belong to the new release. release-manager.sh applies this file during an update.
#
# > Example:
#
# >     prepare-release.sh
#
# > Useful examples:
#
# >     prepare-release.sh --updatebuild
# >     prepare-release.sh --updateversion
# >     prepare-release.sh --bumpminor
# >     prepare-release.sh --bumpmajor
# >     prepare-release.sh --dryrun
#
# > prepare-release.sh is a development/release-authoring tool and therefore uses the
# > normal SolidGroundUX framework runtime.
#
# -- Release Manager -----------------------------------------------------------------
#
# > release-manager.sh is the canonical installation and release-lifecycle tool.
#
# > It replaces the former separate installer, updater, and uninstaller scripts.
#
# > Its state model is intentionally filesystem-based:
#
# >     /var/lib/solidgroundux/releases
# >         Contains downloaded, prepared, or rolled-back releases that are available
# >         for installation.
#
# >     /var/lib/solidgroundux/archive/<release>
# >         Contains releases that have been installed. The highest versioned archive
# >         directory represents the currently installed release.
#
# > No separate current-version database is required. The release directories
# > themselves provide installation history and rollback information.
#
# > A first install consists of validating and extracting a complete release archive.
#
# > A later install is treated as an update. The new release is extracted normally,
# > and its .removed manifest is applied so files that disappeared from the release
# > are removed from the active installation.
#
# > Rollback installs a selected archived release again and removes files that belong
# > only to the newer release. Newer archived releases are returned to releases/ so
# > the highest remaining archive directory continues to represent the active version.
#
# > Removal removes the active release contents and returns archived release sets to
# > releases/, preserving them for later reinstallation.
#
# -- First Installation --------------------------------------------------------------
#
# > GitHub release bundles may contain both release-manager.sh and the prepared release
# > artifacts in one ZIP file.
#
# > A first installation can therefore start from any temporary directory:
#
# >     cd /tmp
# >     unzip SolidGroundUX-<version>-release.zip
# >     sudo ./release-manager.sh --install
#
# > On first run, release-manager.sh:
#
# >     - Creates the SolidGroundUX release-management directories when needed.
# >     - Detects a complete release set beside itself.
# >     - Validates the release artifacts and checksums.
# >     - Admits the release into /var/lib/solidgroundux/releases.
# >     - Installs the release.
# >     - Moves the installed release set into the versioned archive directory.
# >     - Copies itself to /var/lib/solidgroundux/release-manager.sh.
# >     - Cleans only the known temporary bootstrap files after successful installation.
#
# > Because all managed paths are absolute, the bootstrap copy may be run from /tmp
# > or any other convenient directory.
#
# -- Interactive Use -----------------------------------------------------------------
#
# > Running release-manager.sh without an action opens the interactive release menu:
#
# >     sudo /var/lib/solidgroundux/release-manager.sh
#
# > The menu can:
#
# >     - Check GitHub for the latest release.
# >     - Download the latest release.
# >     - Update to the latest release.
# >     - Install the newest locally available release.
# >     - Select an archived version for reinstallation or rollback.
# >     - Remove SolidGroundUX.
#
# > Archived releases are shown in a dedicated submenu, newest first. The current
# > release is marked explicitly, and removal is offered as the final menu option.
#
# -- Command-line Use ----------------------------------------------------------------
#
# > release-manager.sh also supports unattended and scripted operation.
#
# > Check GitHub without changing the machine:
#
# >     release-manager.sh --check
#
# > Download the latest release without installing it:
#
# >     release-manager.sh --download
#
# > Check, download if required, and install the latest GitHub release:
#
# >     release-manager.sh --update
#
# > Install the newest release already available in releases/:
#
# >     release-manager.sh --install
#
# > Install a specific local or archived release:
#
# >     release-manager.sh --install --release 1.8.2622102
#
# > Roll back to the previous archived release:
#
# >     release-manager.sh --rollback
#
# > Roll back to a specific archived release:
#
# >     release-manager.sh --rollback --release 1.8.2621804
#
# > Remove the active SolidGroundUX installation:
#
# >     release-manager.sh --remove
#
# > Run an action without confirmation prompts:
#
# >     release-manager.sh --update --auto
#
# > Preview filesystem changes:
#
# >     release-manager.sh --update --dryrun
#
# > Override the default GitHub repository:
#
# >     release-manager.sh --check --repo Testadura-Mark/SolidGroundUX
#
# > Use a specific ZIP file or URL as the release source:
#
# >     release-manager.sh --update --source /tmp/SolidGroundUX-release.zip
# >
# >     release-manager.sh --update # >         --source https://example.org/releases/SolidGroundUX-release.zip
#
# > Alternate roots can be supplied for testing or recovery:
#
# >     release-manager.sh --install # >         --target-root /mnt/testroot # >         --state-root /mnt/testroot/var/lib/solidgroundux
#
# -- GitHub Acquisition --------------------------------------------------------------
#
# > GitHub is the default authoritative source for determining the latest published
# > SolidGroundUX release.
#
# > release-manager.sh asks GitHub which release is current before downloading.
#
# > If that release is already present under archive/ it is considered installed.
#
# > If it is already present under releases/ it is considered downloaded.
#
# > In either case, the release manager avoids downloading the same release again.
#
# > New downloads are staged in a temporary directory first. The ZIP is extracted,
# > the contained release identity is checked, required release files are verified,
# > checksums are validated, and release paths are checked for unsafe traversal.
#
# > Only a valid release set is admitted into releases/.
#
# -- Relationship to deploy-workspace.sh --------------------------------------------
#
# > deploy-workspace.sh serves a different purpose from release-manager.sh.
#
# > It is intended for rapid development deployment, where selected files from a
# > workspace need to be transferred directly to a test or development machine.
#
# > It supports:
#
# >     - Local or SSH deployment.
# >     - Optional directory filtering.
# >     - Filenames and shell-style masks.
# >     - Changed-after filtering.
# >     - Deployment since the last successful transfer.
# >     - Dry-run operation.
# >     - Persistent deployment settings.
#
# > Example:
#
# >     deploy-workspace.sh # >         --remote sysadmin@td-pdc # >         --source ~/dev/target-root # >         --match '*.sh'
#
# > Incremental deployment:
#
# >     deploy-workspace.sh # >         --remote sysadmin@td-pdc # >         --since-last
#
# > deploy-workspace.sh does not create an installed release record and does not
# > participate in archive-based rollback. It is therefore ideal during development,
# > while prepare-release.sh plus release-manager.sh provide the formal release path.
#
# -- How the Three Tools Relate -------------------------------------------------------
#
# . Images
#   deployment-model :: SolidGroundUX Deployment Model
#
# > This keeps the deployment architecture small, deterministic, and easy to inspect
# > or manipulate directly when necessary.
#
# -- Integrity and Recovery ----------------------------------------------------------
#
# > Release integrity is validated before installation by checking the supplied
# > SHA-256 sidecar files and release paths.
#
# > The release manager intentionally remains independent of the installed framework,
# > its configuration, runtime state, themes, and bootstrap libraries.
#
# > As a result, the canonical copy at:
#
# >     /var/lib/solidgroundux/release-manager.sh
#
# > remains usable for update, rollback, reinstallation, or removal even if the live
# > SolidGroundUX installation is incomplete or damaged.
#
# > This independence is a core deployment design principle.
